using Cassandra.Domain.Common;

namespace Cassandra.Domain.RegistrasiPenjualan.Events;

public record RegistrasiPenjualanCreated(
    RegistrasiPenjualanId Id,
    Guid     DealerId,
    string   NoPenjualan,
    DateOnly SaleDate,
    Guid     KaryawanId,
    Guid     KiosId,
    Guid?    MediatorId,
    string   MetodePenjualan,
    string   TipePenjualan,
    string   NoMesin,
    string   NoRangka,
    string   NamaCustomer,
    string   Address,
    string   Phone,
    string?  Phone1,
    string?  Phone2,
    decimal  OffRoad,
    decimal  Bbn,
    decimal  Discount,
    decimal  ApprovedDiscount,
    decimal  OriginalDiscount,
    decimal  Total,
    decimal  AmbilUang,
    decimal  Dp,
    decimal  Angsuran,
    decimal  Tac,
    Guid?    DaftarHargaLeasingId,
    string?  TenorCode,
    string   TipeMotorCode,
    string   WarnaName,
    string   SerahTerimaKendaraanId,
    string?  TandaTerimaSementaraId,
    string   Kelengkapan,
    bool     IsApproved,
    string   CreatedBy,
    DateTime OccurredAt) : IDomainEvent;
